[project]
name = "scaffolding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.2",
    "typer>=0.13.1",
]

[project.scripts]
cli = "scaffolding.cli.main:app"

[tool.uv]
dev-dependencies = []
